### ISSUE TITLE
robustness

### ISSUE THREAD

**Issue by taywong00** [xshi0603/GeckoSpiders#3]
- removeLast() and removeFirst() dont handle case when queue is empty

**Comment by taywong00** [comment]
- removeLast() if degree is bigger than size 1, it will set front.getNext() to null which should be _end.setNext(null) (line 109) 

[ RESOLVED ]

**Comment by taywong00** [comment]
- didnt test addLast() method in main

[ RESOLVED ]

**Comment by xshi0603** [comment]
fixed
